running in bash

diff --git a/scripts/rootfs_update b/scripts/rootfs_update
--- a/scripts/rootfs_update
+++ b/scripts/rootfs_update
@@ -1,1 +1,23 @@
+#!/bin/bash
 echo 1
+PARAMS=""
+while (( "$#" )); do
+  case "$1" in
+    -f|--flag-with-argument)
+      FARG=$2
+      shift 2
+      ;;
+    --) # end argument parsing
+      shift
+      break
+      ;;
+    -*|--*=) # unsupported flags
+      echo "Error: Unsupported flag $1" >&2
+      exit 1
+      ;;
+    *) # preserve positional arguments
+      PARAMS="$PARAMS $1"
+      shift
+      ;;
+  esac
+done
